/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertModal: typeof import('./src/views/components/alertModal.vue')['default']
    Breadcrumbs: typeof import('./src/views/components/breadcrumbs.vue')['default']
    Icon: typeof import('./src/views/components/icon.vue')['default']
    MdiHome: typeof import('~icons/mdi/home')['default']
    MdiUser: typeof import('~icons/mdi/user')['default']
    MdiViewHeadline: typeof import('~icons/mdi/view-headline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/views/components/sideBar.vue')['default']
    TopMenu: typeof import('./src/views/components/topMenu.vue')['default']
  }
}
